[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.120.4"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  HUGO_EXTENDED = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.120.4"
  HUGO_EXTENDED = "true"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.120.4"
  HUGO_EXTENDED = "true"

[context.next.environment]
  HUGO_BASEURL = "http://www.sumendar.com/"
  HUGO_ENABLEGITINFO = "true"
  HUGO_EXTENDED = "true"
